version: '3.8'

services:
  postgres:
    image: postgres:16.2
    restart: always
    container_name: postgres_db
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - bank_net_bridge
    volumes:
      - project-volume:/var/lib/postgresql/data
    hostname: postgres
    ports:
      - "5433:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: zookeeper_service
    networks:
      - bank_net_bridge
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    networks:
      - bank_net_bridge
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_service:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  bank_ledger:
    build:
      context: .
      dockerfile: Dockerfile
    image: shahabaz4573/banksvc-bank-ledger:1.0
    restart: unless-stopped
    container_name: bank-svc
    depends_on:
      - postgres
    networks:
      - bank_net_bridge
    ports:
      - "50001:50001"
    hostname: bank-svc

  apigw:
    image: shahabaz4573/api-bank-ledger:1.0  
    build:
      context: .
    restart: unless-stopped
    container_name: apigw_svc
    depends_on:
      - kafka
    networks:
      - bank_net_bridge
    ports:
      - "8000:8000"

  notif_ledger:
    image: shahabaz4573/notifsvc-bank-ledger:1.0
    build:
      context: .
    restart: unless-stopped
    container_name: notif-svc
    depends_on:
      - kafka
    networks:
      - bank_net_bridge
    ports:
      - "50002:50002"

networks:
  bank_net_bridge:
    driver: bridge

volumes:
  project-volume:
